### ISSUE TITLE
petg vs pla 

### ISSUE THREAD

**Issue by jeffbrazeau** [GliaX/faceshield#17]
i dont have petg i have lots of pla and resin for my sla printer will they work and then who do i send them to ?

**Comment by tareko** [comment]
Hi!

We haven't tested SLA at all for this. I thought that only some resins were appropriate for medical / FDA use?

Do you mind helping educate me.

tarek : )

**Comment by jeffbrazeau** [comment]
The resin I have is water washable I don’t know how it will react to skin for prolonged contact 

But I have lots of pla for my ender printer 

Will pla work

**Comment by jeffbrazeau** [comment]
Here is the SDS  I don’t know about these things and I am hoping there is someone better then me who knows 

https://cdn.shopify.com/s/files/1/0376/9913/files/PolyJuice-MSDS-NonCasting.pdf

**Comment by lcmyip** [comment]
While I cannot speak for Dr. Loubani, PLA is generally considered a prototyping material, as it is rather brittle and less impact resistant than PETG or ABS. However, if your printer can handle PLA, it can likely also print PETG with minor changes in settings.

I'm not sure that SLA printing would be a cost effective solution for this, especially once you add in the additional post-processing required.

**Comment by amashari** [comment]
PLA is not currently acceptable because of some reports that it is more porous than PETG and ABS and may be more likely to trap virus particles. This is controversial since porocity of prints has numerous factors aside (filament manufacturing process, print settings etc) other than the polymer composition, however it is the current state of the art so we are avoiding PLA.
SLA we have not looked into due to cost and more limited availability of machines. Also most resins are not alcohol resistant. Our cleaning process currently involved household bleach solution so the material would have to be tested with that as well.

**Comment by jeffbrazeau** [comment]
are we not at the point where anything will help pla can be single use
