### ISSUE TITLE
Material : PLA

### ISSUE THREAD

**Issue by gcormier** [GliaX/faceshield#22]
I realize PETG/ABS is recommened, but not everyone can print this, or has stockpiles of filament of a specific type.

https://www.billingsclinic.com/foundation/
https://www.billingsclinic.com/app/files/public/4141/3D-Mask-Directions.pdf

This organization is suggesting PLA. Limiting to PETG/ABS limits the number of possible people who can print them.

**Comment by Compunerd-SSC** [comment]
I printed one with PLA to show the concept to my management and I was too lazy to change the filament.  I can tell you that PLA is not a suitable material as it is much too brittle and will crack in the assembly process.  There may also be other reasons to use specific plastics due to cleaning and sanitization requirements or others considerations.

**Comment by volpex-industries** [comment]
In our experience, heat-treating printed PLA will make it stronger and less brittle.  Are there any other reasons not to use PLA?

**Comment by TokenR** [comment]
From my experience:
PLA is hydrophillic. It absorbs water. It also has a low glass transition temperature. Keep it in the car on a hot sunny day and it will melt and deform. Over time, PLA will crack and deform. Layer adhesion is fair, but not exceptional like PETG or Nylon. It is a more rigid plastic - and while it is good in terms of hardness, it isn't as tough as PETG.

PETG is hydrophobic. It does not absorb water. It has a higher glass transition temperature and it has good layer adhesion. It won't delaminate unless the layers are printed at the wrong temperature. This makes it a better material because it can be reused after gas autoclave decontamination. PETG is food safe and doesn't leech like PLA.

The print uses a "clip" mechanism to hold the shield in place with friction. PLA isn't tough enough to flex and will crack and snap if overstressed.

If your printer hot end can manage 255-260 degrees C and your bed can manage 90 degrees C, PETG should be within reach of your printing capabilities. A lower nozzle temperature risks delamination depending on the brand of PETG you may be using.

**Comment by volpex-industries** [comment]
Heat-treating PLA deals with most of those factors; it ends up stronger and stiffer, and from what I understand is also less porous, which might help against water absorption.  It can make the part shrink a bit, but we can adjust the print for that with some experimentation.  And since this is emergency production for COVID-19, and we'll be producing them for cost of materials, long-term life isn't such an issue as long as they can last long enough to help cover for the PPE shortfall until the proper industrial supply chains get their acts together and produce enough to fill the need.

We'll test our first few as much as we can, of course.  We can go to PETG if we need to, just need some parts (probably just a better bed heater) which will mean delays before we can start production, and it'll mean we need to order a bunch of PETG instead of using all the PLA we already have.

**Comment by TokenR** [comment]
Annealing reflows the plastic's mechanical structure, but the chemical properties of the plastic itself don't change.

This is a high stress situation where mixing materials is not safe. I understand it's an emergency situation - which is why I intend to only print in PETG as it won't fail. One failure at the wrong time would be very very bad, and the lives of those that are being protected by these devices are critical to not only this pandemic, but to the next one.

I would ask that anyone who is printing these to please mark your devices with the material it is manufactured from and with the company/person who manufactured them. If one of us manufactures a large lot of defective items, they must be readily identified and the issues must be isolated. Conversely, if specific items are found to be of better quality, that information can be disseminated to others to bring their manufacturing standard up.

**Comment by tareko** [comment]
Thank you all for your comments. In addition to several infection-control issues (hydrophillic, porous), the mechanical issues are not acceptable. In Gaza, temperatures are routinely high enough to deform PLA parts in routine storage (no electricity, thus no AC). We use ABS there and PETG in Canada as a result.

At the end of the day, we have to make some editorial decisions. This is one of them. I'll close the issue for now, but don't hesitate to continue the discussion as desired.

tarek : )
