### ISSUE TITLE
Bulk stl

### ISSUE THREAD

**Issue by kfrancis** [GliaX/faceshield#24]
My printer can handle much much more of these at a single time, but I'm not sure how to stack these in a good way. Is that something possible? I'm using the [AnyCubic Predator](https://www.anycubic.com/collections/predator-series/products/anycubic-predator-fdm-printer) which has a print volume of 370×370×455mm.

**Comment by mza1979m** [comment]
I would just stack them in whatever way is most optimized, so that you can fit as many on the plate as you possibly can. For example, one of my printers is an AnyCubic Chiron (400x400x450), and I managed to fit 9 on the plate (see screenshot).
![anycubic_chiron](https://user-images.githubusercontent.com/16178388/77808663-a83e9100-7062-11ea-8ae7-be5dad1b9b2f.jpg)

**Comment by kfrancis** [comment]
Yea, ok. That's fine.
