### ISSUE TITLE
New Branch Request - Single Use Disposable Version

### ISSUE THREAD

**Issue by AnimeEd** [GliaX/faceshield#6]
Most health workers are used to single use shields. I'm in contact with a doctor at the local hospital here are some quotes from our discussion

"It's just inconvenient for us to soak
At most they can wipe with a wipe otherwise prob will throw (though later when we are super out of gear it might be different)"

"Vivian Lee: Just putting one patient on a breathing machine you burn through at least 4
For every resp patient you burn through 2 at least"

There is a need for a disposable version (less robust) which is faster to print. One that a single printer can print at least 20 a day.

**Comment by tareko** [comment]
Glia considers disposable face shields wasteful, reckless and a large contributor to our current problem. No institution should use or manufacture disposable face shields.

The current problem is not a lack of PPE, but an excess of disposable PPE that is both destroying our planet and putting healthcare providers at risk due to shortages. Glia is working to end that problem.

After reviewing guidelines, we've reduced soak time to 1 minute. I think that should be fine, and it's hard to believe any institution can't make this happen.

tarek : )
